---
version: 6.5.0
slug: mosquitto-custom
name: Mosquitto custom broker
description: An Open Source MQTT broker
url: https://github.com/oloendithas/ha-addons/tree/main/mosquitto
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
auth_api: true
discovery:
  - mqtt
map:
  - ssl
  - share
options:
  logins: []
  require_certificate: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  customize:
    active: false
    folder: mosquitto-custom
ports:
  2883/tcp: 2883
  2884/tcp: 2884
  8883/tcp: 8883
  8884/tcp: 8884
schema:
  logins:
    - username: str
      password: str
      password_pre_hashed: "bool?"
  require_certificate: bool
  certfile: str
  cafile: str?
  keyfile: str
  customize:
    active: bool
    folder: str
  debug: bool?
services:
  - mqtt:provide
startup: system
watchdog: tcp://[HOST]:2883
init: false
